### ISSUE TITLE
[新增功能]結果圖官網超連結

### ISSUE THREAD

**Issue by LuckyPigeon** [sexyoung/vhpi.5000#1]
## Description
在結果圖上加入導向官網的超連結讓使用者領券更方便。

**Comment by LuckyPigeon** [comment]
@sexyoung 
你的官網 `http://www.sexyoung.tw/` 內容需要幫忙嗎？直接使用預設的 `index page` 會產生資安疑慮喔！

**Comment by sexyoung** [comment]
@LuckyPigeon 該怎麼幫忙啊

**Comment by LuckyPigeon** [comment]
@sexyoung 
最少該把預設頁面換成某個 hello world 吧！不然對於稍微有點概念的就知道那個頁面是 root 了！

**Comment by sexyoung** [comment]
@LuckyPigeon 好哦

**Comment by sexyoung** [comment]
@LuckyPigeon 我改好囉 謝謝提醒 :) :sheep: 也謝謝你送 PR

**Comment by LuckyPigeon** [comment]
@sexyoung 
後續如果有構想，可以加我 `discord: luckypigeon#2663`，可以幫忙貢獻 PR。

**Comment by sexyoung** [comment]
@LuckyPigeon  加囉
