### ISSUE TITLE
[新增功能]提醒日期&面額

### ISSUE THREAD

**Issue by LuckyPigeon** [sexyoung/vhpi.5000#3]
## Description
新增以下功能，讓民眾對券本身有基礎了解，包含：
  * 提醒領券日期
  * 顯示抽中的面額

**Comment by LuckyPigeon** [comment]
@sexyoung 
你可以在這個專案首頁放上 `hacktoberfest` 的標籤嗎? 這個月剛好有 hacktoberfest 活動

**Comment by sexyoung** [comment]
那是什麼呀? 你要不要直接加我 line 討論一下呀?

**Comment by sexyoung** [comment]
@LuckyPigeon add it!
